doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            groupName: App\Infrastructure\Doctrine\Types\Group\NameType
            username: App\Infrastructure\Doctrine\Types\User\UsernameType
            password: App\Infrastructure\Doctrine\Types\User\PasswordType
            roles: App\Infrastructure\Doctrine\Types\User\RolesType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm'
                prefix: 'App\Domain\Entity'
                alias: App
